/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.BikeSharing.kevin;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Kevin
 */
//
public class Portale extends javax.swing.JFrame {
int l=0;
int contatore = 0;
    public Portale() {
       
        try 
        {
        String myDriver = "com.mysql.cj.jdbc.Driver";
        String myUrl = "jdbc:mysql://localhost/test?useUnicode=true&useJDBCComplicantTimezoneShift=true&useLegacyDateTimeCode=false&serverTimezone=UTC";
        Class.forName(myDriver);
        Connection conn = DriverManager.getConnection(myUrl, "root","");
        String query  = "SELECT * FROM users";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(query);
        String cff;
        String pss;
        
        while(rs.next())
        {
            cff=rs.getString("codice fiscale");
            pss=rs.getString("password");
            
            lista.Set(rs.getString("last name"),rs.getString("first name"),rs.getInt("birthday day"),rs.getInt("birthday month"),rs.getInt("birthday year"),rs.getString("sesso").charAt(0),rs.getString("luogo di nascita"),rs.getString("luogo di residenza"),cff,pss,rs.getInt("n_accessi"));
            lista.ToString();
            
        }
        st.close();
        }catch (Exception e) 
        {
            Logger.getLogger(Portale.class.getName()).log(Level.SEVERE, null, e);
        }
        initComponents();   
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        FiscalCodeText2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ShowPassword = new javax.swing.JCheckBox();
        LastNameText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        EmailText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        GenderBox = new javax.swing.JComboBox<>();
        RegisterConfirmButt = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dayText = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        monthText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        YearText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cityofbirthdayText = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cityText = new javax.swing.JTextField();
        PasswordText1 = new javax.swing.JPasswordField();
        PasswordText2 = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FiscalCodeText = new javax.swing.JTextField();
        LoginButt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        RegisterButt = new javax.swing.JLabel();
        PasswordText = new javax.swing.JPasswordField();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(233, 66, 14));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin\\Desktop\\bikesharing.jpg")); // NOI18N

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fiscal Code");

        FiscalCodeText2.setText("Enter Fiscal Code");
        FiscalCodeText2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FiscalCodeText2MouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirm Password");

        ShowPassword.setBackground(new java.awt.Color(51, 51, 51));
        ShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        ShowPassword.setText("show Password");
        ShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPasswordMouseClicked(evt);
            }
        });

        LastNameText.setText("Enter Last Name");
        LastNameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LastNameTextMouseClicked(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Last Name");

        NameText.setText("Enter First Name");
        NameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameTextMouseClicked(evt);
            }
        });
        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("First Name");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email");

        EmailText.setText("Enter Email");
        EmailText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmailTextMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Registration");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gender ");

        GenderBox.setForeground(new java.awt.Color(255, 255, 255));
        GenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        RegisterConfirmButt.setBackground(new java.awt.Color(51, 51, 51));
        RegisterConfirmButt.setForeground(new java.awt.Color(255, 255, 255));
        RegisterConfirmButt.setText("Register");
        RegisterConfirmButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterConfirmButtActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(233, 66, 14));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel6KeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("X");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Date of Birthday");

        dayText.setText("gg");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("/");

        monthText.setText("mm");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("/");

        YearText.setText("aaaa");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("City of birthday");

        cityofbirthdayText.setText("Where you born");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("City ");

        cityText.setText("Where you live");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel21)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(dayText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(monthText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(YearText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel20)
                                .addComponent(cityofbirthdayText)
                                .addComponent(cityText))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(EmailText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NameText, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                        .addComponent(LastNameText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(FiscalCodeText2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(RegisterConfirmButt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(GenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PasswordText1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordText2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(ShowPassword)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FiscalCodeText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(monthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cityofbirthdayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(RegisterConfirmButt)
                .addGap(17, 17, 17))
        );

        jPanel7.setBackground(new java.awt.Color(233, 66, 14));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(22, 22, 22))
        );

        jPanel8.setBackground(new java.awt.Color(233, 66, 14));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Indietro");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel23)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 392, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Login"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(233, 66, 14));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kevin\\Desktop\\bikesharing.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(233, 66, 14));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fiscal Code");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password ");

        FiscalCodeText.setText("Enter Fiscal Code");
        FiscalCodeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FiscalCodeTextMouseClicked(evt);
            }
        });

        LoginButt.setBackground(new java.awt.Color(233, 66, 14));
        LoginButt.setForeground(new java.awt.Color(255, 255, 255));
        LoginButt.setText("Login");
        LoginButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lost your password?");

        RegisterButt.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterButt.setText("Don't have an account?");
        RegisterButt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtMouseClicked(evt);
            }
        });
        RegisterButt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RegisterButtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RegisterButtKeyTyped(evt);
            }
        });

        PasswordText.setText("Passowrd");
        PasswordText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(123, 123, 123)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterButt)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LoginButt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(FiscalCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PasswordText, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FiscalCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(LoginButt)
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterButt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel6KeyTyped
       
    }//GEN-LAST:event_jPanel6KeyTyped

    private void RegisterButtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegisterButtKeyTyped
      
    }//GEN-LAST:event_RegisterButtKeyTyped

    private void RegisterButtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegisterButtKeyPressed
      
    }//GEN-LAST:event_RegisterButtKeyPressed

    private void RegisterButtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtMouseClicked
       jFrame1.setVisible(true);
       jFrame1.pack();
       jFrame1.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_RegisterButtMouseClicked

    private void FiscalCodeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiscalCodeTextMouseClicked
       FiscalCodeText.setText("");
    }//GEN-LAST:event_FiscalCodeTextMouseClicked

    private void PasswordTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTextMouseClicked
        PasswordText.setText("");
    }//GEN-LAST:event_PasswordTextMouseClicked

    private void NameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameTextMouseClicked
        NameText.setText("");
    }//GEN-LAST:event_NameTextMouseClicked

    private void LastNameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastNameTextMouseClicked
        LastNameText.setText("");
    }//GEN-LAST:event_LastNameTextMouseClicked

    private void EmailTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmailTextMouseClicked
        EmailText.setText("");
    }//GEN-LAST:event_EmailTextMouseClicked

    private void FiscalCodeText2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiscalCodeText2MouseClicked
        FiscalCodeText2.setText("");
    }//GEN-LAST:event_FiscalCodeText2MouseClicked
    public void writeDataLineByLine(String filePath) 
    {    
        // first create file object for file placed at location 
        // specified by filepath 
        File file = new File(filePath); 
        try { 
        // create FileWriter object with file as parameter 
        FileWriter outputfile = new FileWriter(file,true); 
        
        // create CSVWriter object filewriter object as parameter 
        BufferedWriter writer = new BufferedWriter(outputfile); 
  
        // adding header to csv 
        // add data to csv 
        writer.write(FiscalCodeText2.getText()+";"+PasswordText1.getText());
        writer.newLine();
        // closing writer connection 
        writer.close(); 
        } 
        catch (IOException e) { 
        // TODO Auto-generated catch block 
        e.printStackTrace(); 
    } 
}
    private void RegisterConfirmButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterConfirmButtActionPerformed
        //controllli
        boolean ok = true;
        for(int i = 0;i < NameText.getText().toCharArray().length;i++){if(Character.isDigit(NameText.getText().charAt(i))){ok = false;}}
        if(ok == false){JOptionPane.showMessageDialog(this,"Non puoi inserire numeri nel campo 'Name'!","errore",JOptionPane.ERROR_MESSAGE);NameText.setText("");}
        for(int i = 0;i < LastNameText.getText().toCharArray().length;i++){if(Character.isDigit(LastNameText.getText().charAt(i))){ok = false;}}
        if(ok == false){JOptionPane.showMessageDialog(this,"Non puoi inserire numeri nel campo 'LastName'!","errore",JOptionPane.ERROR_MESSAGE);LastNameText.setText("");}
        for(int i = 0;i < dayText.getText().toCharArray().length;i++){if(Character.isLetter(dayText.getText().charAt(i))){ok = false;}}
        if(ok == false){JOptionPane.showMessageDialog(this,"Non puoi inserire caratteri alfabetici nel campo 'day'!","errore",JOptionPane.ERROR_MESSAGE);dayText.setText("");}
        for(int i = 0;i < monthText.getText().toCharArray().length;i++){if(Character.isLetter(monthText.getText().charAt(i))){ok = false;}}
        if(ok == false){JOptionPane.showMessageDialog(this,"Non puoi inserire caratteri alfabetici nel campo 'month'!","errore",JOptionPane.ERROR_MESSAGE);monthText.setText("");}
        for(int i = 0;i < YearText.getText().toCharArray().length;i++){if(Character.isLetter(YearText.getText().charAt(i))){ok = false;}}
        if(ok == false){JOptionPane.showMessageDialog(this,"Non puoi inserire caratteri alfabetici nel campo 'year'!","errore",JOptionPane.ERROR_MESSAGE);YearText.setText("");}
        for(int i = 0;i < cityofbirthdayText.getText().toCharArray().length;i++){if(Character.isDigit(cityofbirthdayText.getText().charAt(i))){ok = false;}}
        if(ok == false){JOptionPane.showMessageDialog(this,"Non puoi inserire numeri nel campo 'city of birthday'!","errore",JOptionPane.ERROR_MESSAGE);cityofbirthdayText.setText("");}
        for(int i = 0;i < cityText.getText().toCharArray().length;i++){if(Character.isDigit(cityText.getText().charAt(i))){ok = false;}}
        if(ok == false){JOptionPane.showMessageDialog(this,"Non puoi inserire numeri nel campo 'city'!","errore",JOptionPane.ERROR_MESSAGE);cityText.setText("");}
        //controllare che i campi non siano vuoti
        if(NameText.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"the field 'Name' can't be empty!","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(LastNameText.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"the field 'Last Name' can't be empty!","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(PasswordText1.getText().equals("")||PasswordText2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"password don't match!Retype password again","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(dayText.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"the field 'day birthday' can't be empty!","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(monthText.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"the field 'month birthday' can't be empty!","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(YearText.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"the field 'year birthday' can't be empty!","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        CodiceFiscale pers = new CodiceFiscale();
       // pers.Set(jCOGNOME.getText(), jNOME.getText(),Integer.parseInt(String.valueOf(jComboBox2.getSelectedItem())), Integer.parseInt(String.valueOf(jComboBox3.getSelectedItem())), Integer.parseInt(String.valueOf(jComboBox4.getSelectedItem())), String.valueOf(jComboBox1.getSelectedItem()).toUpperCase().charAt(0), jPAESE.getText().toUpperCase());
         pers.Set(LastNameText.getText().toLowerCase(),NameText.getText().toLowerCase(),Integer.parseInt(String.valueOf(dayText.getText())), Integer.parseInt(String.valueOf(monthText.getText())), Integer.parseInt(String.valueOf(YearText.getText())), String.valueOf(GenderBox.getSelectedItem()).charAt(0), cityofbirthdayText.getText().toLowerCase());
        //cf1.Calcola(LastNameText.getText(),NameText.getText(),Integer.parseInt(dayText.getText()),Integer.parseInt(monthText.getText()),Integer.parseInt(YearText.getText()),String.valueOf(GenderBox.getSelectedItem()).charAt(0),cityofbirthdayText.getText());
        String cf1 = pers.Calcola().toUpperCase();
        boolean controllo[] = new boolean[7];
        String cf = FiscalCodeText2.getText().toUpperCase();
        ok = cv.SetControlloValidità(FiscalCodeText2.getText().toUpperCase().toCharArray());
        if(ok)
        {
            controllo = cv.calcola();
            if(controllo[0]==false){FiscalCodeText2.setText("");JOptionPane.showMessageDialog(this,"Cognome errato","errore",JOptionPane.ERROR_MESSAGE);}
            if(controllo[1]==false){FiscalCodeText2.setText("");JOptionPane.showMessageDialog(this,"Nome errato","errore",JOptionPane.ERROR_MESSAGE);}
            if(controllo[2]==false){FiscalCodeText2.setText("");JOptionPane.showMessageDialog(this,"Anno errato","errore",JOptionPane.ERROR_MESSAGE);}
            if(controllo[3]==false){FiscalCodeText2.setText("");JOptionPane.showMessageDialog(this,"Mese errato","errore",JOptionPane.ERROR_MESSAGE);}
            if(controllo[4]==false){FiscalCodeText2.setText("");JOptionPane.showMessageDialog(this,"Giorno errato","errore",JOptionPane.ERROR_MESSAGE);}
            if(controllo[5]==false){FiscalCodeText2.setText("");JOptionPane.showMessageDialog(this,"Codice Catastale errato","errore",JOptionPane.ERROR_MESSAGE);}
            if(controllo[6]==false){FiscalCodeText2.setText("");JOptionPane.showMessageDialog(this,"Carattere di controllo errato","errore",JOptionPane.ERROR_MESSAGE);}
            if(controllo[0]==true&&controllo[2]==true&&controllo[3]==true&&controllo[4]==true&&controllo[5]==true&&controllo[6]==true)JOptionPane.showMessageDialog(this,"Codice fiscale corretto!","INFO",1);
            if(controllo[0]==false||controllo[2]==false||controllo[3]==false||controllo[4]==false||controllo[5]==false||controllo[6]==false)JOptionPane.showMessageDialog(this,"Codice fiscale non corretto!","ERRORE",JOptionPane.ERROR_MESSAGE);
           
            if(!cf.equals(cf1))
            {
              System.out.println("cf : "+cf+"\ncf1 : "+cf1);
              JOptionPane.showMessageDialog(this, "Reinserisci il codice fiscale perchè non corrisponde ai dati che hai inserito","ERRORE",JOptionPane.ERROR_MESSAGE);
              FiscalCodeText2.setText("");
            }
            else
            {
               JOptionPane.showMessageDialog(this, "I dati sono corretti","INFO",JOptionPane.INFORMATION_MESSAGE);

                if(PasswordText1.getText().equals(PasswordText2.getText()))
                {
                  //gestione con i database
                  PreparedStatement sp;
                  String query = "INSERT INTO `users`(`id`, `first name`, `last name`, `birthday day`, `birthday month`, `birthday year`, `luogo di nascita`, `codice fiscale`, `sesso`, `password`, `luogo di residenza`, `n_accessi`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
                  String n = NameText.getText();
                  String c = LastNameText.getText();
                  int d = Integer.parseInt(dayText.getText());
                  int m = Integer.parseInt(monthText.getText());
                  int a = Integer.parseInt(YearText.getText());
                  String cb = cityofbirthdayText.getText();
                  String fc = FiscalCodeText2.getText();
                  char gb = String.valueOf(GenderBox.getSelectedItem()).charAt(0);
                  String cr = cityText.getText();
                  String code="";  
        try 
        {
            System.out.println("sono nel try catch della registrazione");
            sp = MyConnection.getConnection().prepareStatement(query);
            System.out.println("sto per inserire i dati nel database");
            //Creo un nuovo Utente
            lista.Set(c,n,d,m,a,gb,cb,cr,fc,PasswordText1.getText(),0);
            l++;
            //Creo una nuova riga nel database per il nuovo utente
            sp.setInt(1,contatore);
            sp.setString(2, n);
            sp.setString(3, c);
            sp.setInt(4, d);
            sp.setInt(5, m);
            sp.setInt(6, a);
            sp.setString(7, cb);
            sp.setString(8, fc);
            sp.setString(9, String.valueOf(gb));
            sp.setString(10, PasswordText1.getText());
            sp.setString(11, cr);
            sp.setInt(11, 0);
            if(sp.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(this, "new User add!","info",JOptionPane.INFORMATION_MESSAGE);
                lista.ToString(); 
                lista.CheckUtente();
                
                 
            }
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, "Non è stato possibile creare un nuovo utente!","ERRORE",JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(Portale.class.getName()).log(Level.SEVERE, null, ex);
        }
      
       
    }
    else
     {
        JOptionPane.showMessageDialog(this, "le password non corrispondono","ERRORE",JOptionPane.ERROR_MESSAGE);
        PasswordText1.setText("");
          PasswordText2.setText("");
     }
    
            }
        }
        else
        {
           JOptionPane.showMessageDialog(this, "Il codice fiscale che hai inserito non è lungo 16 caratteri!","ERRORE",JOptionPane.ERROR_MESSAGE);
           FiscalCodeText2.setText("");
        }
        contatore++;
    }//GEN-LAST:event_RegisterConfirmButtActionPerformed
    
    
    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed

    private void LoginButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtActionPerformed
        PreparedStatement ps;
        ResultSet rs;
        String cf = FiscalCodeText.getText();
        String pass = PasswordText.getText();
        String query  = "SELECT * FROM `users` WHERE `codice fiscale` =? AND `password` =?";
        try 
        {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, cf);
            ps.setString(2,pass);
            rs = ps.executeQuery();
            if(rs.next())
            {
                System.out.println("--------------------------");
                System.out.println("Login effettuato!");
                System.out.println("--------------------------");
                //ricerca della pass e del codfiscale nel arraylist di utente
                /*
                for(int i = 0;i < l;i++)
                {
                     if((lista.get(i).getCfiscale().equals(FiscalCodeText.getText())) && (lista.get(i).getPassword().equals(PasswordText.getText())))
                    {
                          System.out.println("--------------------------");
                          System.out.println("Login effettuato!");
                          System.out.println("--------------------------");
                    }
                }*/
               
                PreparedStatement sp;
                String query1 = "INSERT INTO `users`(`id`, `first name`, `last name`, `birthday day`, `birthday month`, `birthday year`, `luogo di nascita`, `codice fiscale`, `sesso`, `password`, `luogo di residenza`, `n_accessi`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?";
                try
                {
                    sp = MyConnection.getConnection().prepareStatement(query1);
                    
                    //null pointer exception classe Utente chiamata Lista
                    if(sp.executeUpdate() > 0)
                    {
                        sp.setInt(1,contatore);
                        sp.setString(2, lista.GetNome());
                        sp.setString(3, lista.GetCognome());
                        sp.setInt(4, lista.GetData()[0]);
                        sp.setInt(5, lista.GetData()[1]);
                        sp.setInt(6, lista.GetData()[2]);
                        sp.setString(7, lista.GetLuogo());
                        sp.setString(8, lista.getCfiscale());
                        sp.setString(9, String.valueOf(lista.GetSesso()));
                        sp.setString(10, lista.getPassword());
                        sp.setString(11, lista.getLuogoDiResidenza());
                         sp.setInt(1, lista.get_N_accessi());
                         String code = lista.Accesso();
                         JOptionPane.showMessageDialog(this, "Ecco il tuo codice : \n"+code,lista.get_N_accessi()+"° accesso",JOptionPane.INFORMATION_MESSAGE);
                    }
                }catch(SQLException ex)
                {
                     JOptionPane.showMessageDialog(this, "Non è stato possibile aggiornare n_accessi!","ERRORE",JOptionPane.INFORMATION_MESSAGE);
                     Logger.getLogger(Portale.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                //non trovato
              JOptionPane.showMessageDialog(this, "incorret password and fiscal code!","errore",JOptionPane.ERROR_MESSAGE);
              FiscalCodeText.setText("");
              PasswordText.setText("");
            }
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(Portale.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*
        boolean trovato=false;
        String csvFile = "C:\\Users\\Kevin\\Desktop\\users.csv";
        BufferedReader br = null;
        String line = "";
        String cvsSplitBy = ";";
        String[] country;
        //lettura del file csv
        try 
        {
        
        br = new BufferedReader(new FileReader(csvFile));
        while ((line = br.readLine()) != null)
        {
        // use comma as separator
        country = line.split(cvsSplitBy);
        //stampa dati csv
        System.out.println("Codice Fiscale : " + country[0] + " , Password : " + country[1]);
        //  if(codCom.equals(country[0]))
        if((FiscalCodeText.getText().equals(country[0]))&&PasswordText.getText().equals(country[1]))
        {
        System.out.println("trovato!");
        trovato = true;
        }
 
        }
        if(trovato==true)
        {
        FiscalCodeText.getText().charAt(0);
        System.out.println("l vale "+l);
        if(l==1) 
        {
        JOptionPane.showMessageDialog(this, "benvenuto/a "+u1.GetNome()+"nel portale bikesharing!","info",JOptionPane.INFORMATION_MESSAGE);
        String code = u1.Accesso();
        JOptionPane.showMessageDialog(this,"Ecco il codice per prendere la bicicletta :\n"+code,"Hai effettuato n°"+u1.getAccesso(),JOptionPane.INFORMATION_MESSAGE); 
        }
        if(l==2)
        {
        JOptionPane.showMessageDialog(this, "benvenuto/a "+u2.GetNome()+" nel portale bikesharing!","info",JOptionPane.INFORMATION_MESSAGE);
        String code = u2.Accesso();
        JOptionPane.showMessageDialog(this,"Ecco il codice per prendere la bicicletta :\n"+code,"Hai effettuato n°"+u2.getAccesso(),JOptionPane.INFORMATION_MESSAGE);
        }
        if(l==3)
        {
        JOptionPane.showMessageDialog(this, "benvenuto/a "+u3.GetNome()+"nel portale bikesharing!","info",JOptionPane.INFORMATION_MESSAGE);
        String code = u3.Accesso();
        JOptionPane.showMessageDialog(this,"Ecco il codice per prendere la bicicletta :\n"+code,"Hai effettuato n°"+u3.getAccesso(),JOptionPane.INFORMATION_MESSAGE);
        }
        }
        else 
        {
        JOptionPane.showMessageDialog(this, "incorret password and fiscal code!","errore",JOptionPane.ERROR_MESSAGE);
        
        }
        }
        catch (FileNotFoundException e)
        {
        e.printStackTrace();
        }
        catch (IOException e)
        {
        e.printStackTrace();
        }
        finally
        {
        if (br != null)
        {
        try
        {
        br.close();
        }
        catch (IOException e)
        {
        e.printStackTrace();
        }
        }
        }
        */
    
    }//GEN-LAST:event_LoginButtActionPerformed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        this.setVisible(true);
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void ShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPasswordMouseClicked
        if(ShowPassword.isSelected())
        {
            PasswordText1.setEchoChar((char)0);
        }
        else
        {
            PasswordText1.setEchoChar((char)8226);
        }
    }//GEN-LAST:event_ShowPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailText;
    private javax.swing.JTextField FiscalCodeText;
    public javax.swing.JTextField FiscalCodeText2;
    private javax.swing.JComboBox<String> GenderBox;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JButton LoginButt;
    private javax.swing.JTextField NameText;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JPasswordField PasswordText1;
    private javax.swing.JPasswordField PasswordText2;
    private javax.swing.JLabel RegisterButt;
    private javax.swing.JButton RegisterConfirmButt;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JTextField YearText;
    private javax.swing.JTextField cityText;
    private javax.swing.JTextField cityofbirthdayText;
    private javax.swing.JTextField dayText;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField monthText;
    // End of variables declaration//GEN-END:variables
    Utente lista = new Utente();
    //CodiceFiscale pers = new CodiceFiscale();
    CodiceFiscale pers1 = new CodiceFiscale();
    ControlloValidità cv = new ControlloValidità();
}